#!/opt/local/bin/perl
# Author: Ng, Tzy Luen
# Date: : Sun Jul 28 13:16:19 MYT 2013
# Desc  : a cozy sunday with sundae
#
use warnings;
use strict;
use Data::Dumper;
use DBI;

my $host = shift(@ARGV);
die "-E- host undefined\n" unless $host;

if (!grep { /^$host$/ } qw(localhost)) {
    print "-E- invalid $host\n";
    exit(1);
}

my($db,$port,$user,$password,$sock) = qw(information_schema 3306 root xyz /tmp/mysql.sock);
my $dbh = DBI->connect("DBI:mysql:$db:$host;port=$port;mysql_socket=/tmp/mysql.sock",$user,$password,
            {PrintError => 1}) or die "$DBI::errstr\n";

&checksum();

sub checksum {
    my $pstmt = $dbh->prepare("SELECT `table_schema`, `table_name` FROM `tables`");
    $pstmt->execute();
    while (my $row = $pstmt->fetchrow_hashref()) {
        my $pchksum = $dbh->prepare("CHECKSUM TABLE ".$row->{'table_schema'}.".".$row->{'table_name'});
        $pchksum->execute();
        my $_row = $pchksum->fetchrow_hashref();
        print "$_row->{'Table'}|$_row->{'Checksum'}\n";
    }
}
