#!/opt/local/bin/perl
use warnings;
use strict;

die "-E-".__FILE__." f1 f2" unless scalar @ARGV > 1;
my $this = shift(@ARGV);
my $that = shift(@ARGV);
die "-E- $this undefined\n" unless -e $this;
die "-E- $that undefined\n" unless -e $that;

&readsum($this);
&readsum($that);
&verify();

sub readsum {
    my $f = shift;
    my $h = {};
    open(FD, "<$f") or die $!;
    while (<FD>) {
        /(.+)|(.+)/;
        print $1;
        #$h->{$1} = $2;
    }
    return $h;
}


sub verify {
    my $src = shift;
    my $dest = shift;
    &readsum($src);
    &readsum($dest);
}
