#!/opt/local/bin/perl
use warnings;
use strict;

die "-E-".__FILE__." f1 f2" unless scalar @ARGV > 1;
my $this = shift(@ARGV);
my $that = shift(@ARGV);
die "-E- $this undefined\n" unless -e $this;
die "-E- $that undefined\n" unless -e $that;

my $src = &readsum($this);
my $dest = &readsum($that);
&verify($src, $dest);

sub readsum {
    my $f = shift;
    my $h = {};
    open(my $FD, '<', "$f") or die $!;
    while (my $l = <$FD>) {
        $l =~ /([a-zA-Z._0-9]+)\|([0-9]+)/;
        $h->{$1} = $2;
    }
    return $h;
}


sub verify {
    my $src = shift;
    my $dest = shift;

    for my $t (sort keys %{$src}) {
        if (exists $dest->{$t}) {
            print "$t ";
            print "$src->{$t} == $dest->{$t}\n";
        }
    }
}
